=== paroar/DAW/DAW1/Lenguaje-Marcas/2ºevaluacion/catalogoLibro/Documento2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:all>
        <xs:element name="libro" maxOccurs="unbounded"/>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo"/>
              <xs:element name="autor"/>
              <xs:element name="fecha"/>
            </xs:sequence>
            <xs:attribute name="categoria" type="xs:string"/>
            <xs:attribute name="enstock" type="xs:string"/>
            <xs:attribute name="revisor" type="xs:string"/>
          </xs:complexType>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== paroar/DAW/DAW1/Lenguaje-Marcas/2ºevaluacion/catalogoLibro/Documento1.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Documento2.xsd">
<libro categoria="noficcion" enstock="false" revisor="">
        <titulo>Los hombres que no amaban a las mujeres</titulo>
        <autor>Stieg Larsson</autor>
        <fecha>2000</fecha>
</libro>

<libro categoria="noficcion" enstock="false" revisor="">
        <titulo>Java a través del tiempo</titulo>
        <autor>Pepe</autor>
        <fecha>2000</fecha>
</libro>

</catalogo>
